### ISSUE TITLE
Update tests after Mockito with stable automatic module name is released

### ISSUE THREAD

**Issue by zyxist** [zyxist/chainsaw#1]
After Mockito releases the following PR: https://github.com/mockito/mockito/pull/1195 , update the unit tests to use the new module name: `org.mockito`.

**Comment by zyxist** [comment]
New version published, but not yet to Maven Central:

https://github.com/mockito/mockito/releases/tag/v2.10.5

**Comment by deepy** [comment]
Isn't this resolved by 90336d81055faf32010e46e4c617cbb59b9e9fb5?

**Comment by zyxist** [comment]
Actually, it is, thanks :+1:
