### ISSUE TITLE
Don't do anything, if there is no src/main/java directory

### ISSUE THREAD

**Issue by zyxist** [zyxist/chainsaw#11]
In a multi-project setup, root project usually does not have `/src/main/java` directory - the sources are in the subprojects. However, the new module name detector fails, if it does not find `module-info.java` descriptor.

There is a workaround for that:

```groovy
javaModule.name = ''
```

It is a bit ugly. Generally, if there is no directory with the sources, we should skip parsing `module-info.java` at all.

**Comment by Vampire** [comment]
You could also mix module-enabled projects and non-module-enabled projects (auto-modules).
So you should probably not depend on whether the source directory is present, but whether there is a `module-info.java`?
And also there could be multiple source sets, so you shouldn't only pimp the `main` source set, but also the other source sets?

**Comment by Vampire** [comment]
Yep, I just hit having a non-module-enabled project and your plugin chickens out
